name: Playwright Tests

on: [push]

jobs:
  playwright:
    name: 'Run Playwright Tests in Docker'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies (if any, e.g., specific test runner or reporter not in image)
       
      - name: Run Playwright tests
        run: npx playwright test

  
